### ISSUE TITLE
Automate the release pipeline and fix missing haddock

### ISSUE THREAD

**Issue by TerrorJack** [tweag/haskell-binaryen#10]
**Is your feature request related to a problem? Please describe.**
Currently, the Hackage release of `binaryen` is performed manually. It would be nice if we can create and upload Hackage sdists as a part of the CI pipeline. Additionally, CI should produce the haddock tarball in this process, since the Hackage servers won't be able to build them anyway due to missing foreign dependency.

**Describe the solution you'd like**
* [ ] Implement CI logic to produce sdist and upload to Hackage. Whether or not to run the job should depend on git metadata (branch/tag).
* [ ] Also build and upload haddock documentation tarball.

**Comment by mboes** [comment]
https://xkcd.com/1205/

**Comment by mboes** [comment]
https://xkcd.com/1205/

**Comment by TerrorJack** [comment]
CI now produces sdist/haddock tarballs, so this is semi-automatic. Fully automating the upload is indeed not worth the effort yet.
