### ISSUE TITLE
Implement new interfaces in `version_92`

### ISSUE THREAD

**Issue by TerrorJack** [tweag/haskell-binaryen#9]
**Is your feature request related to a problem? Please describe.**
Our initial version is based on `version_91`. `version_92` has introduced breaking changes in C API, so a new major release which targets `version_92` should be cut. The new interfaces in the C API should also get their Haskell bindings.

`nixpkgs` has just [updated](https://github.com/NixOS/nixpkgs/commit/2869edcb51d177978a25a3bbe1f58cc53a6a8234) `binaryen` to `version_93`, and debian updated to `version_92`. Thus it's good timing to do this upgrade.

**Describe the solution you'd like**
* [ ] Implement new interfaces in `version_92`
* [ ] Release `binaryen-0.0.2.0`
* [ ] Use `binaryen-0.0.2.0` in `asterius`, and deprecate `binaryen-0.0.1.1`, since `0.0.1.1` actually already depends on `version_92` and onwards.

**Comment by TerrorJack** [comment]
Closed via #12. Only addressed the breaking changes.

**Comment by mboes** [comment]
Could use the opportunity to have one fewer zeros in the prefix of the version number...
